name: tradebot

services:

  tradebot:
    container_name: tradebot
    image: a2k0001/tradebot
    build:
      context: .
      dockerfile: Dockerfile
    command: -p ${TIMESCALEDB_PORT}
    volumes:
      - ./.env:/app/.env
      - database:/home/postgres/pgdata/data
      - ./config:/app/config
    ports:
      - ${TIMESCALEDB_PORT}:${TIMESCALEDB_PORT}
    expose:
      - ${TIMESCALEDB_PORT}
    environment:
      - POSTGRES_PASSWORD=${TIMESCALEDB_PASSWORD}

volumes:
  database: