FROM timescale/timescaledb:latest-pg17

RUN apk update && apk add nodejs npm tmux

COPY ../package.json /app/package.json
COPY .tmux.conf /root/.tmux.conf

WORKDIR /app
RUN npm install --omit=optional --omit=dev
